apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-jackexperts
  template:
    metadata:
      labels:
        app: desafio-jackexperts
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 755 /usr/share/nginx/html; echo 'Permissions set'"]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: my-pvc
