name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker image
        run: |
          docker build -t devopsfelipe/jackexperts-desafio:latest .
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u devopsfelipe --password-stdin
          docker push devopsfelipe/jackexperts-desafio:latest
